### ISSUE TITLE
Wrong registration number being used for related organizations?

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/orgbook-bc-client#100]
Examples:
- https://orgbook.gov.bc.ca/entity/BC0928747
- https://orgbook.gov.bc.ca/entity/FM0414526

In the credential timeline of the example records the registration number listed for each of the related organizations is the registration number of the organization being viewed (see screenshots below).

Should the registration numbers be for the listed (related) organization itself and not that of the organization being viewed.

All registration numbers are listed as `BC0928747`:
![image](https://user-images.githubusercontent.com/10504350/146939468-968e8dde-aa95-4169-a663-41415a351c92.png)

All registration numbers are listed as `FM0414526`:
![image](https://user-images.githubusercontent.com/10504350/146940023-1836a43e-f805-4314-9b23-0fffd7783374.png)

**Comment by WadeBarnes** [comment]
In the screenshot below the two records actually refer to the same related organization; https://orgbook.gov.bc.ca/entity/FM0414526

![image](https://user-images.githubusercontent.com/10504350/146942467-26a7b46d-521b-44cd-aea2-e2c1c3097a05.png)

![image](https://user-images.githubusercontent.com/10504350/146942604-954cde69-b64d-46bf-982a-ebbe88c914e4.png)

**Comment by swcurran** [comment]
I think this should be addressed when @wadeking98. For a relationship, the display should probably be "Relationship description" and "Associated registration id" claims.  Don't know how easy that is with the design we have, so we'll have to see what's possible.

**Comment by swcurran** [comment]
Priority for cleanup
