### ISSUE TITLE
Rename this repo to "orgbook-bc-client" and rename the old one to "orgbook-bc-client-angular"?

### ISSUE THREAD

**Issue by swcurran** [bcgov/orgbook-bc-client#104]
I think it is time...

**Comment by amanji** [comment]
@WadeBarnes Are you able to rename https://github.com/bcgov/orgbook-bc-client to `orgbook-bc-client-angular`? I don't have the correct permissions to. I can rename this repo. Wondering if we should just outright archive the older repo as well?

**Comment by WadeBarnes** [comment]
I'll rename the repos.  This has to be done in coordination with other CI/CD updates otherwise this repo once renamed will be built as if it's the old one.

**Comment by WadeBarnes** [comment]
Done

**Comment by WadeBarnes** [comment]
A retirement notice has been added to [orgbook-bc-client-angular](https://github.com/bcgov/orgbook-bc-client-angular) and the repo has been archived.
