### ISSUE TITLE
Fix word-wrap on mobile devices

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/orgbook-bc-client#106]
Reported by @DJ-Gordon.

When possible can somebody take a look at the line breaking for the links on the main page. It does not look great on Mobile when “OrgBook” break.

![image](https://user-images.githubusercontent.com/10504350/147287903-8a32d177-0848-4008-8679-c27f39263c51.png)

**Comment by WadeBarnes** [comment]
Fixed, tested in `prod`.  Users will have to refresh the page if they have visited the site previously.

**Comment by WadeBarnes** [comment]
@DJ-Gordon, could you retest and confirm this is fixed, please?

**Comment by DJ-Gordon** [comment]
Yes. Looks much better.

[cid:3407F993-E24A-4750-A6A7-663A189A50AF-L0-001]

Thanks for the quick fix.

D

Sent from my iPhone

On Dec 27, 2021, at 8:04 AM, Wade Barnes ***@***.***> wrote:

﻿

[EXTERNAL] This email came from an external source. Only open attachments or links that you are expecting from a known sender.


@DJ-Gordon<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDJ-Gordon&data=04%7C01%7CDwayne.Gordon%40gov.bc.ca%7Ce6204283db134f69551e08d9c95275be%7C6fdb52003d0d4a8ab036d3685e359adc%7C0%7C0%7C637762178840231098%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=4soLEfOBxKqsQANih%2FgaDbgOcT6uqVsHbyfzlM26QoY%3D&reserved=0>, could you retest and confirm this is fixed, please?

—
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbcgov%2Forgbook-bc-client%2Fissues%2F106%23issuecomment-1001634350&data=04%7C01%7CDwayne.Gordon%40gov.bc.ca%7Ce6204283db134f69551e08d9c95275be%7C6fdb52003d0d4a8ab036d3685e359adc%7C0%7C0%7C637762178840231098%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HhBi%2BJvAvK51ejnIdk2OpsRbku31jkuAYmzavifq5q0%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEWHWFRS62ZZ2BN33NBEJ6TUTCE6BANCNFSM5KVNZC7Q&data=04%7C01%7CDwayne.Gordon%40gov.bc.ca%7Ce6204283db134f69551e08d9c95275be%7C6fdb52003d0d4a8ab036d3685e359adc%7C0%7C0%7C637762178840231098%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=D1rcO7PD0HrpAM2f3s1p5K8l%2BFoAr5lz7QwIkWUZUC4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CDwayne.Gordon%40gov.bc.ca%7Ce6204283db134f69551e08d9c95275be%7C6fdb52003d0d4a8ab036d3685e359adc%7C0%7C0%7C637762178840231098%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=CxdJn30p5N1ZxnOyQzdPxrag4q9pYUUWGbWYLW4Eedk%3D&reserved=0> or Android<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CDwayne.Gordon%40gov.bc.ca%7Ce6204283db134f69551e08d9c95275be%7C6fdb52003d0d4a8ab036d3685e359adc%7C0%7C0%7C637762178840231098%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Q9QhDqi1DkhFkvzfFEIVOfkNdyFdS5rQ7uuTdurlnRk%3D&reserved=0>.
