### ISSUE TITLE
Help text for main search and search results

### ISSUE THREAD

**Issue by swcurran** [bcgov/orgbook-bc-client#140]
We've had feedback that searchers have had trouble with some searches, especially when punctuation is involved.  We want to provide some guidance for those searching on the home page near the "Find an organization" autocomplete widget and on the search results page near the "XXX result(s)" indicator.  Basically, we need two buttons/icons/links and for each a popup with text that I can provide.

The issues I'm trying to address are these, from the "dislike" comments we've received:

- `I searched for "BKV Social Enterprise Co." and I received 1295 results. This does not help me to find the BC Registry ID because I neither have the time nor inclination to search through that many results. The previous version of OrgBook would have returned the result (FM0824270) I was searching for. Return only results for the exact search entered NOT all Business names that contain similar words.` (this is an example of the punctuation problem -- had they just searched "BKV", they would have had only 3 results
- `advanced search  - i can't sift through 1500+ results.  ability to refine searches though the search terms, not just the categories` (likely same as above)

- when the organization name contains punctuation, the searching is bad. On the main page we need to help them with that.
- at times many, many results come up and we want to provide them guidance that we have about that.

I'd like @alexgmetcalf to weigh in on the UI element -- the buttons/icons/links to be used.  Alex -- please mock up some images for what to use in the two places.

Here is a first cut of the text to use in both places. Alex/others -- feel free to improve on this. Worst case, we start with this and we can evolve it as needed:

Help Text

> The OrgBook searching by legal name returns all of the organizations that have any of the words that you search on, and floats the most likely matches to the top of the list. In most cases, that means that putting the fully legal name of the entity will float that result to the top. However, in some cases you may find that you get both many (many!) search results, and the entity you are looking for is not at the top. This most often happens when the legal name has punctuation marks -- for example a period "." at the end of the name, e.g. "Co." or "Inc.". It's a problem with the search tool we are using -- we're working on a fix!
> 
> When you get too many results and the name you are looking for is not at the top, we recommend that you put only the least common word (or two) from the name. For example, when searching for "BKV SOCIAL ENTERPRISE CO.", about 1300 results are returned, with the top ones having "Social" in them. That darn trailing period! In this case "BKV" is the least common word, so let's only search for that by typing "BKV" into the search bar and hitting ENTER (e.g. don't pick anything from the drop down list).  The result is now just a couple of entries, one of which is the one we want.
>
> Remember as well that with OrgBook, you don't have to search on the legal name. You can also search on the BC Registries ID (has two characters and 7 digits, like FM1234567) and by the CRA Business Number (9-digits) for the entity. If you know one or both of those values, using those for an existing entity will always find an exact match.
>
> If you still can't find the entity you are looking for (and you are pretty sure it exists), please use the "Contact" link at the top of the page to let us know what you are looking for and that you can't find it, and we'll see if we can help.

**Comment by WadeBarnes** [comment]
In the case of "BKV Social Enterprise Co.":
- Searching for "BKV Social Enterprise Co." returns 50951 results.  BKV Social Enterprise Co. is in the top 3.
- Searching for "BKV Social Enterprise Co" returns 1285 results.  BKV Social Enterprise Co. is in the top 3.
- Searching for BKV Social Enterprise Co. returns 1285 results.  BKV Social Enterprise Co. is not even on the first page.
- Searching for BKV Social Enterprise Co return 1282 results.  BKV Social Enterprise Co. is not even on the first page.

When using any of the above search terms BKV Social Enterprise Co. is the first in the list for auto-complete.  But when you click on it either nothing happens (no search is initiated) or you end up with the same result set as if you used the term, BKV Social Enterprise Co., where the company name you just picked out of auto-complete is not even on the first page.
![image](https://user-images.githubusercontent.com/10504350/152178176-ff56b4ef-403c-4abf-88f4-307e9eb3e092.png)

What's changed with search?  This is not a very intuitive experience.

Yes in the case of this company they could have just searched for "BKV", but what about the many cases where there isn't a distinct word in the name.  You should be able to perform a full string search using `""` to narrow the results.

**Comment by swcurran** [comment]
Thanks, Wade -- that's great.  I'll adjust the help to try to highlight that.

I don't think anything has changed on the search.  When you click on a drop down entry it uses the entry you clicked, with no quotes, so no difference from your 3rd item in your list.  Pretty sure that's always been the behaviour. 

Another weird one:

* Searching for BKV ENTERPRISE CO. returns no results.  What???

So this tells me the hint should include "not enough" and "too many" results.

And we need to adjust the guidance to mention the use of quotes.

Search is hard...

**Comment by wadeking98** [comment]
closed after help text merged
