### ISSUE TITLE
Remove larger text and bold on "Relationship" links

### ISSUE THREAD

**Issue by swcurran** [bcgov/orgbook-bc-client#149]
For example, on: https://test.orgbook.gov.bc.ca/entity/FM0239928b

The link for the owning entity "WESTCOAST HOBBIES 4 U LTD." is in (I think) a larger font and bold. I don't think that is needed.

I suggest also making it a bulleted (unordered) list vs. just a line of text.

When done locally, please add screenshots before PRing this change.

Thanks

**Comment by wadeking98** [comment]
Bullets on relationship credentials
![image](https://user-images.githubusercontent.com/36937407/154585647-05c84972-c270-427e-b23f-41d3e5d50ff2.png)
Bullets on expired relationship credentials
![image](https://user-images.githubusercontent.com/36937407/154585796-6c8cb981-e39b-4b2a-92a1-60d9105ac13e.png)

**Comment by swcurran** [comment]
The "owned" by does not have the bullet (see below).  It should be every relationship is displayed the same way.  While in there, I think we should ditch any explicit <br> between the "Credential Expired..." and the link to the relationship entity (see screenshot above).  If it is just a natural line wrapping that is OK, but if it is an explicit line break, I think it should be removed.

![image](https://user-images.githubusercontent.com/1018050/154706191-bf1e6242-e9e8-4770-a3d9-7138b8dd3cf3.png)
