### ISSUE TITLE
Change text "expired" on Relationships section of entity page

### ISSUE THREAD

**Issue by swcurran** [bcgov/orgbook-bc-client#151]
I noticed that the "expired" appears in the "Relationships" tab. See: https://orgbook.gov.bc.ca/entity/BC0338518

In that case, it is the organization that has been dissolved - not the credential. As such, the text should say "Historical", not expired, and the date should be the effective date of the dissolution -- e.g. for https://orgbook.gov.bc.ca/entity/FM0562397 it should be Oct 01, 2019.

See if this is an obvious change. If not, we can discuss the related data in a meeting with @ianco and the BC Registries folks.

**Comment by wadeking98** [comment]
The text is straightforward, but the date doesn't seem to be an obvious change. Right now there's no way to grab the dissolution date from a relationship credential, because the dissolution date exists on a different credential. We will have to meet to discuss a work around.

**Comment by swcurran** [comment]
If the "expired" refers to the credential, then it should be prefixed with "Credential" to make it clear.

Would that solve your problem?

**Comment by wadeking98** [comment]
Yes that would work

**Comment by wadeking98** [comment]
closed by PR: https://github.com/bcgov/orgbook-bc-client/pull/159
