### ISSUE TITLE
Add Matomo Analytics

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/orgbook-bc-client#156]
Please add matomo analytics.

Example of how it was done in the Angular client version:
- https://github.com/bcgov/orgbook-bc-client-angular/blob/f37d06baac316d5732683cc3096cac79b70017f8/src/index.html#L10-L24

More information on our matomo deployment can be found here; https://github.com/BCDevOps/matomo-openshift

**Comment by wadeking98** [comment]
Is this a replacement to snowplow?

**Comment by WadeBarnes** [comment]
No, in addition to.

**Comment by swcurran** [comment]
I just got some screenshots from the GDX Analytics and wonder if we need both.  I don't have an IDIR and so can't see what's in Snowplow.  @WadeBarnes -- can you take a look and see if you think we need the Matomo at all.  That implementation was never great, as the requests often took too long to be useful.

Thanks

**Comment by WadeBarnes** [comment]
I don't think we need both.  Apologies, I thought you had seen the GDX analytics results and were asking for Matomo to be hooked back up for some reason.  I should have inquired more.

**Comment by wadeking98** [comment]
Should I close this issue then?
