### ISSUE TITLE
Link to issuing Authority not working

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/orgbook-bc-client#160]
Example corp: https://orgbook.gov.bc.ca/entity/BC0432724

In the credential history scroll down to the Buy BC Logo Licensee and open it up.
![image](https://user-images.githubusercontent.com/10504350/159771693-d355be84-5c61-4a35-9319-511f218a6214.png)

Click on the **Investment Agriculture Foundation BC** link.

Expected behavior:
- The link would take you to a page providing more information about the issuing authority.

Actual Behavior:
- Takes you back to the page your already on, the corp's page.

**Comment by WadeBarnes** [comment]
This issue seems to affect the issuing Authority links of any credentials that is not associated to the BC Corporate Registry, so all credentials from:
- Liquor and Cannabis Regulation Branch
- Ministry of Energy, Mines and Low-carbon Innovation
- Investment Agriculture Foundation BC
- Ministry of Environment and Climate Change Strategy

**Comment by WadeBarnes** [comment]
This is due to the fact the issuers, other than BC Corporate Registry have not registered a URL that would be used for this link.  The issuer registrations can be found here; https://orgbook.gov.bc.ca/api/v2/issuer.

The default in this case is to have the issuing Authority link link back to the corporation to which the credential was issued.

**Comment by WadeBarnes** [comment]
This default behavior is a little confusing.  I'm wondering if it would be better for the link to go to a generic Issuing Authority page that displays the registration information (and logo if one is registered) for the issuer.  In all cases there is an email address registered for the issuers, but that information is inaccessible through the current UI.

**Comment by WadeBarnes** [comment]
@swcurran, Thoughts?

**Comment by swcurran** [comment]
First, I would encourage us to go back to the issuers and get the URLs and add them in. @DJ-Gordon -- is that something you can do?  I assume once we have them, we can add them easily to the database?

That said, what do we do if we don't have them?

I'd suggest one of two behaviours:

- No link
- Link to this page: https://orgbook.gov.bc.ca/about/orgbook-data

I don't think it worth adding another page specifically for this situation as it encourages bad behaviour by the issuers -- not supplying the needed info.

Personally, I think I would go with no link.
