### ISSUE TITLE
Please add these companies to Org Book TEST 

### ISSUE THREAD

**Issue by afillier** [bcgov/orgbook-bc-client#164]
Hello, 
Could we please have these test corporations added to ORG BOOK TEST? Let me know if you need any additional information.
Thank you!! 
Alanna 
1. FASTER TRUCKS CORP. - BC1026852
2. TOP TIER TRUCKING CORP. - BC1026853
3. ARBUTUS COURIERS CORP. - BC1026854
4. TONY'S TAXIS CORP. - BC1026855

**Comment by swcurran** [comment]
@amanji -- with Ian out, can you please take care of this?

**Comment by swcurran** [comment]
Progress on this @amanji -- we're you able to get to this?

**Comment by amanji** [comment]
These are now available in `test`. Closing as completed.

**Comment by afillier** [comment]
thank you @amanji !!
