### ISSUE TITLE
Do we have all of the "Entity Type" descriptions

### ISSUE THREAD

**Issue by swcurran** [bcgov/orgbook-bc-client#165]
At the top of this file is a list of all entity types: https://github.com/bcgov/orgbook-bc-client/blob/main/src/i18n/en.json

There is some additional info on some of the entity types here: https://github.com/bcgov/orgbook-bc-client/tree/main/src/entityDescriptions

Since we don't have an MD file for every entity type, what do we do when displaying an entity type for which we don't have a file?  My concern is that we are showing a default description -- likely the "BC" entry.  If so, that would be a Bad Thing. 

Please at least check the code and see what we are doing in this area of the code. Once we know that we can decide as a group how to proceed.

Thanks

**Comment by swcurran** [comment]
Assigning to Wade for the code check.  Heads up about this @DJ-Gordon @amanji

**Comment by wadeking98** [comment]
I believe if we don't have the entity type then we display the raw value of the entity type. Example if we didn't have this line here https://github.com/bcgov/orgbook-bc-client/blob/8e390bc2dc8c2c085b8839830ba9c650ecbd35ce/src/i18n/en.json#L17 then any profession company would be displayed as `entity_type.PC`

**Comment by swcurran** [comment]
Does that include the information pop up for the entity type?

**Comment by wadeking98** [comment]
yes, that is how it's handled everywhere. The translation function we use to convert the raw value to a human readable value will return the raw value if it can't find the human readable one.

**Comment by wadeking98** [comment]
yes it seems like it defaults to the bc-company markdown file. What should I change the default behavior to be?

**Comment by swcurran** [comment]
That's bad.  

How about this.  Create a Markdown file (say, "Undefined.md") with (initially) no text in it. If we don't have a Markdown File, just print the name of the entity type as found here: https://github.com/bcgov/orgbook-bc-client/tree/main/src/entityDescriptions, a carriage return, and then dump the "Undefined.md" text.

Then, perhaps with help from @DJ-Gordon -- we can get a file from Registries that has suitable text to go into the "Undefined.md", about all of the entity types we have that don't have a detailed description.  We'll just update "Undefined.md" with that text when it is available.

As well, @DJ-Gordon could you see if we can get more markdown files that have details of other entity types?  We need text to go into a file for each (or many) entity type to go into this folder: https://github.com/bcgov/orgbook-bc-client/tree/main/src/entityDescriptions

**Comment by swcurran** [comment]
Text to use follows below.  If you cannot extract/display the Entity Type (first two characters), leave that line off.

Bonus points if you can put: "Entity Type: \<code\>, \<value\>" in the first line, where the code and value are the entity types from this table -- https://github.com/bcgov/orgbook-bc-client/blob/main/src/i18n/en.json


```
Entity Type: XX

Entity Type description is not available in OrgBook BC.

If you need additional information, please contact BC Registry Services via email [bcregistries@gov.bc.ca](mailto:bcregistries@gov.bc.ca), or by calling the BC Registries Help Desk at [1-800-663-6102](tel:18006636102).
```
