### ISSUE TITLE
MOTI request: add companies to OrgBook Test

### ISSUE THREAD

**Issue by StephanieForbes** [bcgov/orgbook-bc-client#169]
Please add these companies to OrgBook Test to allow us to align with ICBC test. ICBC test has inc. no's for 2 of the companies (listed below) if that is helpful but no BNs for any:
  *   CONTINENTAL SINGERS
  *   BAKKEN GOLD TRANSPORT
  *   CHAHAL ALBERTA TRANSPORTATION LTD
  *   B.C. EXCAVATING INC
  *   RFR CONSULTING SERVICE INCORPORATED - 1042343
  *   INTERNATIOAL FREIGHT SERVICES 
  *   RJ GRANITE COUNTERTOPS LTD. - 0933556

**Comment by amanji** [comment]
Do you have the Registration Numbers for these companies?

**Comment by StephanieForbes** [comment]
@amanji  - I will ask but I'm not optimistic :-)

**Comment by StephanieForbes** [comment]
@amanji - no we don't. thanks

**Comment by amanji** [comment]
@ianco Can we query by name for the registration numbers?

**Comment by amanji** [comment]
I've done a search query against COLIN Production and the only companies I am able to find are:
RFR CONSULTING SERVICE INCORPORATED - 1042343
RJ GRANITE COUNTERTOPS LTD. - 0933556

@ianco is there another place I should query against?

**Comment by amanji** [comment]
@StephanieForbes 

I ran a query in the Test COLIN database and I'm not able to find the companies. @ianco confirmed he wasn't able to find them either.  The two companies listed above with Registration Numbers are in the Production database but those will not map over to OrgBook Test. Any chance you can confirm those names with your team? We can also set up a call if that helps?

**Comment by afillier** [comment]
Thanks @amanji @ianco 
It makes sense that some may be in PRD, but we were hoping to add these companies to OrgBook Test to allow us to align with ICBC test. A call would work, to try to give you a background of the situation. 
Let me know when is best for you - I am free Monday afternoon other than between 3-330. :) 
FYI @StephanieForbes

**Comment by ianco** [comment]
In order to add rhe companies in OrgBook test they need to be first added into BC Reg test (COLIN or LEAR depending) and then we can sync the data into OrgBook

**Comment by afillier** [comment]
Thanks @ianco I was hoping there might have been a manual way to work around for that in the test environment. If not, I will follow up with BC Registries as their name approval process in test has changed, will update you when these have been completed to then add to org book, thank you!

**Comment by afillier** [comment]
Hi @ianco and @amanji   I have now been able to create at least one sole proprietorship through BC REG/LEAR. 
I wanted to confirm this is the information required and that this test account is set up correctly to be added with the current set up before I go through the process in LEAR again. Can you let me know if this is enough information to have them added into ORG book test? If that works I will send a few more for set up, please let me know if you need any more information. 

Name Request Number: NR 5428131
Business Name: SPEED SECRETS TRUCKING COMPANY
Business Number: 990900508BC0001

Thank you!! 
Alanna

**Comment by afillier** [comment]
Hello again @ianco @amanji  

I have added the additional items into BC registries for sole proprietors, and the second group into COLIN for corporations. Could these please be added into OrgBook TEST, please let me know if any other information is required. Thank you! 


- SPEED SECRETS TRUCKING COMPANY 
NR 5428131BC Sole Proprietorship
Business Number: 990900508BC0001

- URBAN LEGEND TRUCKING 
NR 2603230BC Sole Proprietorship 
BN: 990858003BC0001

- ISLAND HOPPER TRUCKING COMPANY	
NR 3581959BC Sole Proprietorship
BN: 990894701BC0001

- TOTAL TAXI
NR 1713604BC Sole Proprietorship
BN: 990894503BC0001

- TOWN TOWING
NR 0546479BC Sole Proprietorship
BN: 990894305BC0001

- NEW TRUCKS	
NR 1093439 BC Sole Proprietorship
BN: 990894107BC0001 

Corporations: 

- GLOBE TROTTER TRANSPORT INC.
NR 9331997BC Limited Company
Incorporation Number:    BC1053747	

- SUNRISE AND SUNSET TRIPS CORP.
NR 7129178 BC Limited Company
Incorporation Number:    BC1053748	

- CLOCKWISE TRUCKING CORPORATION
NR 4170698BC Limited Company
Incorporation Number:    BC1053749	

- EXPLORE EXPRESS INC.
NR 5901150BC Limited Company
Incorporation Number:    BC1053750	

Thank you! 

Alanna

**Comment by ianco** [comment]
Hi @afillier 
Thanks for the update, I'll try to take a look at this today (no promises I'm heads-down in another issue right now) (if not today then tomorrow)
Ian

**Comment by ianco** [comment]
Hi @afillier 
I've processed these companies, let me know if they look ok.
FYI the "TOTAL TAXI" company was named "ON-THE-DOT TRUCKING COMPANY" in the database (I did the lookup based on the BN).
Also FYI it's best if you can give us the BC company number (for sole props this will be something like "FM1234567")

**Comment by afillier** [comment]
Hi @ianco  thank you very much for all your help on these requests! 
I will include the registration number as noted in the future. 
Thanks, Alanna
