### ISSUE TITLE
Special Characters not handled correctly in UI

### ISSUE THREAD

**Issue by ianco** [bcgov/orgbook-bc-client#171]
See companies FM0621413 and FM0591650. The names don't seem to be displayed correctly in the UI (special characters) however the credential data (in the database) seems to be correct

**Comment by amanji** [comment]
I'm not entirely sure if the characters are being stored correctly in Postgres. I'm still investigating but this is the output I see in PgAdmin:

![Image](https://github.com/bcgov/orgbook-bc-client/assets/5605464/f2515ed5-5efe-4163-9516-300e385e2c1c)

This seems to impact how the names are displayed on the frontend.

**Comment by amanji** [comment]
It appears the name is also stored incorrectly in BC REG: `ENTRE NOUS (LE CLUB FRANÃAIS)`.

**Comment by amanji** [comment]
@ianco I might need your help on this one.

**Comment by ianco** [comment]
If the name isn't correct in COLIN/LEAR then there's not much we can do.  All we do is take the info in COLIN (or LEAR) and post it to OrgBook.

**Comment by amanji** [comment]
Going to close this then unless there needs to be some escalation.

**Comment by swcurran** [comment]
As long as OrgBook is showing the same as what’s in the BC Registries database, it is doing the right thing. Fixing things in the BC Registries Databases isn’t our problem.
