### ISSUE TITLE
BN from Historical Credential Displayed on Organization Page in OrgBook BC

### ISSUE THREAD

**Issue by swcurran** [bcgov/orgbook-bc-client#175]
A business owner has reported that at the top of the page for their organization, the BN showing is from an historical credential.  See this page: https://orgbook.gov.bc.ca/entity/FM0867097.  From what I can see, the credentials on the page are correct. The two active credentials (Registration and BN credentials) are correct, with the correct BN. However, at the top of the org page, the BN that is displayed immediately below the Legal Name is not the current BN, it is from a record that has been replaced with a newer BN.

The page in question is: https://orgbook.gov.bc.ca/entity/FM0867097
The current BN begins with 8, the older BN begins with 7.

Please investigate where the problem is coming from, and investigate what other organizations are impacted by this issue.

Thanks

**Comment by swcurran** [comment]
@esune -- assigning you for re-assignment as appropriate.

**Comment by ianco** [comment]
It looks like a UI issue.  The credential data (retrieved by https://orgbook.gov.bc.ca/api/v4/topic/2393585/credential-set) looks correct, it looks like the UI is just picking the first BN credential rather than the active one.

**Comment by swcurran** [comment]
Thanks, @ianco . @esune — can you get someone on this ASAP.  @wadeking98 last worked on it, but perhaps someone else should do this.

**Comment by esune** [comment]
Assigning @wadeking98 based on most recent activity on the component. @amanji might be able to take over as well.

**Comment by WadeBarnes** [comment]
Assigning to myself for deployment.

**Comment by WadeBarnes** [comment]
@wadeking98, I'm still seeing an issue here (https://orgbook.gov.bc.ca/entity/FM0867097):
![image](https://user-images.githubusercontent.com/10504350/225314765-219ce7a3-0c39-4dd2-bc1b-a0f7376dde9c.png)

Chronologically 809058589 is the newer one:
![image](https://user-images.githubusercontent.com/10504350/225315561-30ea3e1f-6a60-4582-83e2-190ae29d770d.png)

**Comment by WadeBarnes** [comment]
Updates deployed to `prod`, issue resolved (https://orgbook.gov.bc.ca/entity/FM0867097):
![image](https://user-images.githubusercontent.com/10504350/225319752-a253bd8a-5050-4bfa-a543-ad8c6a633390.png)
