### ISSUE TITLE
Please add companies to OrgBook TEST 

### ISSUE THREAD

**Issue by afillier** [bcgov/orgbook-bc-client#179]
Hello @amanji @ianco  Could you please add the following companies into OrgBook TEST?

Thank you, 
Alanna 

1. MARCH MADNESS CORP.
NR 8214808
BC1056501

2. JJ MOVING CORP.
NR 6317520
BC1056502

3. FAST CAR COMPANY INC.
NR 5532476
BC1056503

4. SAFE CARS INC.
NR 1788791
BC1056505

5. TOY TRUCKS CORP.
NR 9955752
BC1056506

6. ROYAL RACERS CORP.
NR2726684
BC1056507

**Comment by swcurran** [comment]
@esune — FYI about this.  @amanji knows the process.

**Comment by amanji** [comment]
These have now been added to OrgBook TEST. Closing as complete.

**Comment by afillier** [comment]
thank you @amanji!
