### ISSUE TITLE
Printing problem on OrgBook BC — unreadable output

### ISSUE THREAD

**Issue by swcurran** [bcgov/orgbook-bc-client#183]
A user printed the output from BC Registries on a printer and got a bit of mess.  

Please investigate to see if this is fixable or if we can provide documentation guidance to avoid this.

[2023-06-07 Rio Tinto Alcan Inc registered in BC as extraprovincial.pdf](https://github.com/bcgov/aries-vcr/files/11681496/2023-06-07.Rio.Tinto.Alcan.Inc.registered.in.BC.as.extraprovincial.pdf)

**Comment by amanji** [comment]
Going to transfer this to `orgbook-bc-client`. More of a UI issue than to do with the API.

**Comment by swcurran** [comment]
Thanks!

**Comment by WadeBarnes** [comment]
FYI, I tested with my printer and also printed to PDF.  I did not see the same issue as in the example file.

**Comment by swcurran** [comment]
Weird — what might cause this for some people, but not others?  Happy to close, but would be nice to be able to tell others what the issue might be...

**Comment by amanji** [comment]
Tested this on both desktop and mobile Safari. Output seems to be normal (see attached files)
[Desktop.pdf](https://github.com/bcgov/orgbook-bc-client/files/15112778/Desktop.pdf)
[Mobile.pdf](https://github.com/bcgov/orgbook-bc-client/files/15112790/Mobile.pdf)
