### ISSUE TITLE
Extraprovincial company with missing DBA records - Clicking the DBA links results in an empty entity page.

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/orgbook-bc-client#184]
While fixing a related sync issue with a company I came across the fact that none of its related DBA relationship records exist in the OrgBook, and I'm wondering if this is expected.
- If not, we need to determine why the records are missing.
- If so, we need to address the UI/UX issue with being able to open empty entity pages.

Affected Company:
- https://orgbook.gov.bc.ca/entity/A0120859

There are 3 DBA relationships associated to this company (5 records total, two of which have been replaced), none of which exist in the OrgBook.  The result when you click on them is an empty entity page:

![image](https://github.com/bcgov/orgbook-bc-client/assets/10504350/d005e3c4-7644-4ad9-a095-18ad2fd9138b)

**Comment by amanji** [comment]
Seems to have been resolved (see screenshot):

![image](https://github.com/bcgov/orgbook-bc-client/assets/5605464/3802a1d1-64c5-4390-9765-f79b840fa2a0)
