### ISSUE TITLE
Test Org Book 

### ISSUE THREAD

**Issue by afillier** [bcgov/orgbook-bc-client#186]
Hi @amanji and @ianco 
Has something changed in the orgbook test environment? For some reason I am no longer able to find the companies that we had previously added. 
I am using the same link as far as I can tell: https://test.orgbook.gov.bc.ca/search

Please let me know if there is something I missed. 
Also, would it be possible to have any societies that exist in orgbook test identified? I am unable to find any of the ones we previously created, but we can use any society for our testing. I am unable to find any currently: 

![image](https://github.com/bcgov/orgbook-bc-client/assets/96211081/4059997d-da46-4e7b-808b-13c2196872e8)

Thanks, Alanna

**Comment by swcurran** [comment]
@amanji / @WadeBarnes — do we have a way to restore all the companies created on OrgBook Dev/Test for MOTI testing?

We need to get these back ASAP.

@esune — FYI.

**Comment by amanji** [comment]
So far the only way I've been able to is incrementally posting the credentials. It seems to only work in batches of 18k but with 3M that will take a long time to complete.

**Comment by swcurran** [comment]
Can we prioritize getting the ones for MOTI loaded?  Then we need to meet on the rest and discuss.

**Comment by afillier** [comment]
Thanks!! 
Our most urgent would be these three societies (or really any 2 societies that we could use for testing), if that helps with prioritizing. 
I found these in ICBC so I am hoping they might correspond to something that could be added manually but if not let me know :) 
S0042376
S1001025
S0003923

**Comment by afillier** [comment]
Hello @swcurran and @amanji  do you have any update on the above? Thank you!!

**Comment by esune** [comment]
Hello @afillier , we are in the process of re-loading the data into our Test instance. Unfortunately, there isn't a way of selecting which credentials are processed and loaded first. As it stand right now, it should take around another day or so to have the test system loaded with all the credentials - pelase see https://github.com/bcgov/von-bc-registries-agent/issues/331#issuecomment-1692244649

**Comment by afillier** [comment]
thanks @esune  for the update!

**Comment by WadeBarnes** [comment]
@afillier, the three society records you were looking for are available in the `test.orgbook.gov.bc.ca` instance now.
> S0042376
> S1001025
> S0003923

Along with many others:
![image](https://github.com/bcgov/orgbook-bc-client/assets/10504350/380cf518-790a-4d69-8ad1-35f565ca8c95)

**Comment by afillier** [comment]
Thank you!! @WadeBarnes

**Comment by WadeBarnes** [comment]
All of the BC Reg credentials have been reprocessed and are loaded into the OrgBook; https://github.com/bcgov/von-bc-registries-agent/issues/331#issuecomment-1695546377
