### ISSUE TITLE
Orgbook Test update: Company name change

### ISSUE THREAD

**Issue by jonargue** [bcgov/orgbook-bc-client#199]
Company Name:  0879912 B.C. LTD.
Company Incorporation # BC0879912

Hi,

This is another test data update for the MOTI PTM project - can you please update Orgbook test?

Thanks!

**Comment by amanji** [comment]
<img width="1512" alt="Screenshot 2023-10-11 at 9 14 45 AM" src="https://github.com/bcgov/orgbook-bc-client/assets/5605464/f0739703-d213-473f-a403-554f1372b027">

Closing as completed (please see screenshot)
