### ISSUE TITLE
Org name update in Orgbook Test

### ISSUE THREAD

**Issue by jonargue** [bcgov/orgbook-bc-client#201]
Incorporation # BC0878626
Org Name: 0878626 B.C. LTD.

Can you please update the record in orgbook test?

thanks!

**Comment by swcurran** [comment]
Over to you, @amanji !

**Comment by amanji** [comment]
<img width="2514" alt="Screenshot 2023-10-18 at 1 56 52 PM" src="https://github.com/bcgov/orgbook-bc-client/assets/5605464/cd3744a9-66e6-482a-a4da-0b6c41acfbcf">

Closing as completed (see screenshot above)
