### ISSUE TITLE
New test sole proprietorship - WILLY WONKA CANDY

### ISSUE THREAD

**Issue by jonargue** [bcgov/orgbook-bc-client#204]
Hi,

Can you please add the following sole proprietorship to Orgbook test?

WILLY WONKA CANDY
BN# 987894409BC0001
Registration #: FM1111997
Business Start Date: November 16, 2023

Thanks!

**Comment by swcurran** [comment]
Over to you, @amanji !

**Comment by jonargue** [comment]
Hi @amanji - just wondering if you'll be able to get to this in the next week

**Comment by swcurran** [comment]
@esune — we didn’t get to these :-(.  Sorry @jonargue .

@WadeBarnes — can you do this and the two requests that @jonargue requested.

**Comment by WadeBarnes** [comment]
Yes, I can look into this.

@jonargue, confirming it's just the three requests here; https://github.com/bcgov/orgbook-bc-client/issues/created_by/jonargue

**Comment by esune** [comment]
@jonargue sorry, I forgot to follow-up. We queued processing of credentials for TEST to incorporate these entries, however it looks like we may have not imported from LEAR before so the credential import process was slowly picking up results. This was a couple of weeks back though, so the credential should have been processed/added.

I will double check with @WadeBarnes what we can do given the mass import required to include this new corp.

**Comment by WadeBarnes** [comment]
@jonargue, Here you go; https://test.orgbook.gov.bc.ca/entity/FM1111997
