### ISSUE TITLE
New test sole proprietorship - JACK NICHOLSON TRANSPORT 

### ISSUE THREAD

**Issue by jonargue** [bcgov/orgbook-bc-client#205]
Hi,

We have another test sole prop. Can this be added to Orgbook test?

thanks!

Registration Number: FM1112042
Business Number: 987890803BC0001
Business Name: JACK NICHOLSON TRANSPORT 
Business Start Date: November 20, 2023

**Comment by swcurran** [comment]
@amanji — for you, please.

**Comment by jonargue** [comment]
Hi @amanji - just wondering if you'll be able to get to this in the next week

**Comment by WadeBarnes** [comment]
@jonargue, Here you go; https://test.orgbook.gov.bc.ca/entity/FM1112042
