### ISSUE TITLE
Test societies to add to Orgbook test

### ISSUE THREAD

**Issue by jonargue** [bcgov/orgbook-bc-client#211]
Hi,
Could you please add the following test Societies to Orgbook test?

VICTORIA AUTO SOCIETY
S1001147
BN: 98778 3107 BC0001

MILL BAY SHIPPING SOCIETY
S1001148
BN: 98778 2505 BC0001

Thanks!

**Comment by swcurran** [comment]
Over to you @amanji !

**Comment by jonargue** [comment]
Hi @amanji - just wondering if you'll be able to get to this in the next week

**Comment by WadeBarnes** [comment]
@jonargue, Here you go:
- https://test.orgbook.gov.bc.ca/entity/S1001147
- https://test.orgbook.gov.bc.ca/entity/S1001148
