### ISSUE TITLE
Test company to be updated (name change)

### ISSUE THREAD

**Issue by jonargue** [bcgov/orgbook-bc-client#212]
Hi,

Can you update the test orgbook record for this company? It's a name change.

New name: KATALON CARRIERS LTD.
Incorporation # BC0879833
BN: 999450901BC0001

Thanks!

**Comment by amanji** [comment]
Closed as completed (see before and after screenshots)

![Image](https://github.com/bcgov/orgbook-bc-client/assets/5605464/a8d3139e-4c4c-4263-84aa-16fcddba9338)

![Image](https://github.com/bcgov/orgbook-bc-client/assets/5605464/44ff4829-1e8a-4be3-8a3c-8174432c7092)
