### ISSUE TITLE
Recent updates to the Aries-VCR API have broken OrgBook

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/orgbook-bc-client#222]
After deploying the latest updates to both Aries-VCR and the OrgBook-BC-Client, the OrgBook is broken.  There are likely other issues, and they are likely all related to the update to the API which redirects to API `/v4` by default, but here are two to start.

## Issue 1
Steps to reproduce:
- https://dev.orgbook.gov.bc.ca/
- Search for `test`
- Click on the second result `TEST COOP TEST`

Result:
- A blank page:
![image](https://github.com/bcgov/orgbook-bc-client/assets/10504350/51f1f9fc-cc25-40d5-95ab-ea50c74256e8)

Expected Result:
- The company details to be displayed.

## Issue 2

Steps to reproduce:
- From the blank page above.  Click on the BC Icon in the top left corner.

Result:
- A blank page:
![image](https://github.com/bcgov/orgbook-bc-client/assets/10504350/d00d3c24-6dd1-4306-a882-48850cd69889)

Expected Result:
- To return to the main search page:
![image](https://github.com/bcgov/orgbook-bc-client/assets/10504350/52b4ae07-6f40-4aad-adbb-51e8aad446d4)

**Comment by WadeBarnes** [comment]
OrgBook monitoring also needed to be updated.  Not so much of an issue as the monitoring should use a specific API, but it does help to indicate the breadth of the impact of the change.

**Comment by amanji** [comment]
Seems like the call to `/quickload` is failing because of the redirect. Might need to amend the API to add it as a /v4 endpoint or call `/v2` directly in the web app

**Comment by amanji** [comment]
I don't believe anything else relies on `/v2` by default so updating the web app will be the easiest fix

**Comment by WadeBarnes** [comment]
`/api/quickload` is not the only API call being affected.

![image](https://github.com/bcgov/orgbook-bc-client/assets/10504350/1be74559-7403-419c-88b5-3437f27f89e9)

I'm sure there are others.
