### ISSUE TITLE
Suggestions for the Search menu

### ISSUE THREAD

**Issue by swcurran** [bcgov/orgbook-bc-client#37]
I find the current ("make it like Amazon") filters difficult to understand.

Here is what I would suggest:

- the numbers should remain with the full list counts after an update due to filtering.
- the "See more" should only list an entity if it has a non-zero count. If there are none, I would leave the "See more" off.
- once an item is picked in a category, add a "Clear" in that category on the left side menu.

Happy to discuss these further and what complexities these introduce.

**Comment by amanji** [comment]
Wondering if we can retire the `inactive` search URL parameter. Here are my thoughts:

* This is not a generic Aries-VCR or credential concept, however the logic is embedded within Aries-VCR and the generic search interface.
* We can still query and filter for active/historical entities through the application of `entity_status` category filters. Especially in light of the changes to filtering we want to make that successively expand the result set as filters are applied.

Thoughts on this?
