### ISSUE TITLE
Regression -- being able to search for all credentials of a given type

### ISSUE THREAD

**Issue by swcurran** [bcgov/orgbook-bc-client#70]
In the Old OrgBook UI, the advanced search feature has commonly used in demos to find a company with a specific type of credential.  This is probably the only use of the "advanced search".  Not particularly useful, but great for demos when you don't know the names of companies that have a specific type of credential.  We (and especially @watkinspd  and @jljordan42 ) would like that "Show me a list of companies with a given credential".

One idea for doing that, might be on this screen (image below), where we show all the credential types. Could the credential types be a link or perhaps have a "magnifying glass" search icon beside them that when clicked went to the search screen showing a list of that credential type. 

Open to other ideas of how to get this feature back.  Will it screw up the new search screen (because its using a different API or search parameters), or can we get to the search screen in that context?

![image](https://user-images.githubusercontent.com/1018050/146282800-001f8c50-10be-4a2c-aadb-97948c0fbbd4.png)

**Comment by swcurran** [comment]
Not a showstopper for launch, but would definitely like to know if the new search results screen can be retrofitted to do this type of search if we can find a good place from which to trigger it?

**Comment by swcurran** [comment]
@wadeking98 -- priority for cleanup.

**Comment by wadeking98** [comment]
I took the approach of just having a dropdown menu instead of a page with links. It seems simpler and more user friendly to me

**Comment by swcurran** [comment]
I'm sure it is fine -- but can I see a screen shot?

**Comment by wadeking98** [comment]
![image](https://user-images.githubusercontent.com/36937407/150883950-0b10a84b-76f6-4b85-8866-4c8b531e3d4c.png)
![image](https://user-images.githubusercontent.com/36937407/150884040-53ef69b2-56ae-4bbb-abdb-28a3c9a80389.png)
![image](https://user-images.githubusercontent.com/36937407/150884054-b23737cd-da88-4ec4-9e5c-6759ad183c48.png)

**Comment by swcurran** [comment]
This is not ideal for a number of reasons:

- Where this goes (search by credential type) is not an expected definition of "Advanced Search". One of the findings of the UX Research was that the feature was confusing, and by just having "Search by Credential Type" it's even less "advanced".
- The feature is really only used to demonstrate certain credentials.  It's not a feature "real users" have a lot of use for.
- Based on the first two items -- we don't want this on the main page.

Someday we may implement a true "Advanced Search", but this ain't it :-).

Please revert this and implement the approach described in the issue.
