### ISSUE TITLE
Terms of service link

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/orgbook-bc-client#73]
The terms of service link on this page, https://frontend-v2-test.apps.silver.devops.gov.bc.ca/about/orgbook-api, links to The Apache License info here; https://github.com/bcgov/orgbook-api/blob/main/LICENSE.

It should link to an actual terms if service page, which describe the terms of service for the API.

**Comment by swcurran** [comment]
Assigning this to @DJ-Gordon.  @WadeBarnes -- can you add him (Dwayne) to the BCGov org, so we can assign him issues?

What are the terms of use, and once found we can added them in a page to this repo.

Or should they be somewhere else?

**Comment by WadeBarnes** [comment]
Added @DJ-Gordon to the repo for the moment.  We'll be able to assign him the ticket once he accepts the invite.

**Comment by swcurran** [comment]
@DJ-Gordon -- can you please provide the content for this.  We need to get this added.

Or, should we just remove it entirely -- the link and all?

**Comment by DJ-Gordon** [comment]
Let's remove the link for now.  

I am getting confirmation if we can leverage the open-gov terms of use statement, for Orgbook data.
https://www2.gov.bc.ca/gov/content/data/open-data/open-government-licence-bc 

Do we have a comment in the API results, that states license or  "terms of use"?  Similar to what we did on BC Laws?
Example: https://www.bclaws.gov.bc.ca/civix/content/complete/statreg/

**Comment by swcurran** [comment]
@wadeking98 -- please remove the link.

@DJ-Gordon -- the API does not currently have a "terms of use" comment. See [this example](https://orgbook.gov.bc.ca/api/v4/credential-type?paging=false) showing it's not there.  Please add a new issue when you sort out what we should do.  I like the ideas that you mention above.
