### ISSUE TITLE
Inconsistent use of information pop ups

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/orgbook-bc-client#76]
Example: https://frontend-v2-test.apps.silver.devops.gov.bc.ca/entity/FM0389260

On the company results page, the left hand column has inconsistent use of information pop ups:

![image](https://user-images.githubusercontent.com/10504350/146610687-1196ca7b-ee74-4b2e-b283-7e7217652669.png)

The titles Credentials, Authority and Registration type all have info pop ups, but Credential type, Date effective, and Show Expired do not.  Show Expired is somewhat self explanatory, however the others could use info pop up for consistency.

**Comment by swcurran** [comment]
To be assigned to @DJ-Gordon to define the text, and then to @wadeking98 to add in.

**Comment by wadeking98** [comment]
In this conversation here: https://github.com/bcgov/orgbook-bc-client/issues/31#issuecomment-946120547. Credential type is not needed as per @alexgmetcalf 's comment. I'll add the wording for `date effective` and `show expired` though once I get the wording

**Comment by swcurran** [comment]
Priority for cleanup.
