### ISSUE TITLE
License or Permit number search not working

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/orgbook-bc-client#77]
The new UI advertises you can search by permit number.  This is not working.
![image](https://user-images.githubusercontent.com/10504350/146611817-491731d2-1596-4f02-9ea8-5309be14ce02.png)

Using the permit number from here; https://test.orgbook.gov.bc.ca/en/organization/registration.registries.ca/BC0091892/cred/3580366

The new UI turns up zero results; https://frontend-v2-test.apps.silver.devops.gov.bc.ca/search?q=M-238&category%3Aentity_type=&credential_type_id=&inactive=&page=1

![image](https://user-images.githubusercontent.com/10504350/146611954-dcce4f06-20b1-41c3-9d3c-f271d8a2f015.png)

**Comment by swcurran** [comment]
@amanji -- for now, "fix" this by removing "License or Permit" number, and then assign this to @wadeking98 for when he returns.  If this has not yet been designed, we'll likely need a meeting and a plan to figure out how to get this added to the searching.  Should be configurable, and perhaps it would be taken care of by an update to the other issuers (Hmmm...as I write this, I suspect this is the case...).

**Comment by WadeBarnes** [comment]
Similarly, and expectedly based on the comment from @swcurran, License number search does not work either. 

Taking the license number from here; https://test.orgbook.gov.bc.ca/en/organization/registration.registries.ca/BC0803848/cred/3580890

The new UI produces zero results; https://frontend-v2-test.apps.silver.devops.gov.bc.ca/search?q=18C-0039&category%3Aentity_type=&credential_type_id=&inactive=&page=1

![image](https://user-images.githubusercontent.com/10504350/146612457-37a3ea3e-998c-4dbf-b23b-4e5074a9aa25.png)

**Comment by amanji** [comment]
This is not yet a feature that's been implemented. So I'll remove the label for now but we will need to design this.

**Comment by WadeBarnes** [comment]
Reopening the issue so we don't loos it.  The mitigation of removing the labeling has been fixed in `test`.

**Comment by swcurran** [comment]
Closing this issue as resolved and opening a new issue to enable the feature.
