### ISSUE TITLE
Next and previous page buttons are enabled even when there are no additional pages to display

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/orgbook-bc-client#87]
In the **Relationships** section of the company details screen the next and previous page buttons always enabled, even when there are no other pages to display.

Example records:
- https://frontend-v2-prod.apps.silver.devops.gov.bc.ca/entity/BC0722797
- https://frontend-v2-prod.apps.silver.devops.gov.bc.ca/entity/BC0928747

![image](https://user-images.githubusercontent.com/10504350/146784634-b602fb04-5cc1-45ac-b606-3af0d887e361.png)

![image](https://user-images.githubusercontent.com/10504350/146784670-dc55a177-9855-4ce4-9e01-43c0ead47eb0.png)

Similarly the previous button is enabled even when on the first page of a multi-page display:
![image](https://user-images.githubusercontent.com/10504350/146788129-aadda526-d279-444f-869d-2f6429b7c133.png)

and the next button is enabled even when on the last page of a multi-page display:
![image](https://user-images.githubusercontent.com/10504350/146788293-e898f8aa-f68f-4b00-8b75-4ace349ca604.png)

**Comment by WadeBarnes** [comment]
@swcurran, I think this one could wait for @wadeking98 to do; thoughts?

**Comment by swcurran** [comment]
Yes - not needed for launch.

**Comment by swcurran** [comment]
Priority for cleanup.
