### ISSUE TITLE
Changing the number of relationship items to display does not adjust the page display

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/orgbook-bc-client#88]
Example record: https://frontend-v2-prod.apps.silver.devops.gov.bc.ca/entity/BC0928747

Steps to reproduce:
- View the relationships for the example record.
- Set the number of **Items displayed** to 100.
- Now change the number of **Items displayed** to a smaller number.

Observed behavior:

The page starts out looking like this:
![image](https://user-images.githubusercontent.com/10504350/146786775-f8704f35-589e-4993-8b59-00f3e99eb725.png)

The page ends up looking like this:
![image](https://user-images.githubusercontent.com/10504350/146786887-19f73aa7-3b15-4d08-b353-d563895d20f3.png)

Similarly if you change from a smaller number to a larger number you end up with this:

Before:
![image](https://user-images.githubusercontent.com/10504350/146787584-0572c90c-1eb3-406b-9516-9e0727bdee3b.png)

After:
![image](https://user-images.githubusercontent.com/10504350/146787650-e5218250-f062-4f4a-995c-b7d153c4619e.png)

Expected behavior:
The display to re-focus to the top of the **Relationships** like this, whenever the **Items displayed** is changed:
![image](https://user-images.githubusercontent.com/10504350/146787224-6c48ad4b-f54a-4662-93b3-fe11a93dfea1.png)

**Comment by WadeBarnes** [comment]
@swcurran, I think this one could wait for @wadeking98 to do; thoughts?

**Comment by swcurran** [comment]
Yes - not needed for launch.

**Comment by swcurran** [comment]
Priority for cleanup
