### ISSUE TITLE
Credential verified links not working when opened in a new tab

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/orgbook-bc-client#93]
Example: https://frontend-v2-prod.apps.silver.devops.gov.bc.ca/entity/BC0928747

![image](https://user-images.githubusercontent.com/10504350/146830729-1fd0b92d-d14a-4d2e-ae7a-405d1353a011.png)

Right click on the Credential verified links and select open link in new tab.

![image](https://user-images.githubusercontent.com/10504350/146831886-fa1a8bc0-0834-4de1-9fdd-addc716b5900.png)

The new tab opens to the OrgBook home page:

![image](https://user-images.githubusercontent.com/10504350/146831990-63db5c35-8026-49d7-a672-2a3f0f4f9723.png)

Rather than the expected credential detail page:

![image](https://user-images.githubusercontent.com/10504350/146831004-6320a889-d38c-42a9-b1f7-1ca88a31a81a.png)

**Comment by WadeBarnes** [comment]
Same happens if you try to open the links from one of the credentials in the timeline list.

![image](https://user-images.githubusercontent.com/10504350/146832491-6999275c-4327-4d7e-8f23-741e36594135.png)

**Comment by swcurran** [comment]
Priority for cleanup.
