### ISSUE TITLE
Navigating to one link and then back again looses your place on the first page

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/orgbook-bc-client#94]
Example: https://frontend-v2-prod.apps.silver.devops.gov.bc.ca/entity/BC0928747

Locate a credential in the list and click on the **Credential verified** link to view the credential:
![image](https://user-images.githubusercontent.com/10504350/146832947-e2465bf9-b12b-4966-93d0-0b0146a89d27.png)

![image](https://user-images.githubusercontent.com/10504350/146832970-d3d36fe1-823e-421b-9e08-b1ab1302ce3a.png)

Now click the link to go back to the company detail screen.  You end up at the top of the page and the credential you had opened is now closed, so you have completely lost your place on the page.

![image](https://user-images.githubusercontent.com/10504350/146833157-7e506e60-9b4b-4052-b778-ec1ebb9161f5.png)

**Comment by swcurran** [comment]
Please investigate this. If too complex, add a comment about what you find (if anything) and move this to the icebox.  If not too complex, please implement.
