### ISSUE TITLE
Ctrl-Clicking on a relationship link opens the credential status for the record.

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/orgbook-bc-client#96]
Example record; https://frontend-v2-prod.apps.silver.devops.gov.bc.ca/entity/BC0928747

`ctrl-click` a relationship link.  The link to the related record opens as expected in a new tab, however the operation also drops open the credential status for the record:

![image](https://user-images.githubusercontent.com/10504350/146836195-8ef91ca4-9d49-4709-9df8-32e717da42c1.png)

Right-click, open link in new tab does not do this.  It leaves the credential status collapsed and opens the link in a new tab as expected.

![image](https://user-images.githubusercontent.com/10504350/146836256-4b3b0998-0991-4d0a-a9d5-1a19086c3e31.png)

**Comment by WadeBarnes** [comment]
This is a usability issue stemming from the fix for https://github.com/bcgov/orgbook-bc-client-vue/issues/86

**Comment by swcurran** [comment]
Priority for cleanup.
