### ISSUE TITLE
Navigating to a relationship record and back again is a little tricky

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/orgbook-bc-client#97]
Example record: https://frontend-v2-prod.apps.silver.devops.gov.bc.ca/entity/BC0928747

Click on a relationship record to view it.

![image](https://user-images.githubusercontent.com/10504350/146838916-f6c50ead-a6b4-4385-9d26-3ba1bb4b5f8b.png)

To navigate back to the original record you have to click the browser's back button or use an equivalent method (shortcut, back button on a mouse, etc.), as the page itself does not provide a link back to the previous record, only to the main search screen.

**Comment by WadeBarnes** [comment]
This is a usability issue stemming from the fix for https://github.com/bcgov/orgbook-bc-client-vue/issues/86

**Comment by amanji** [comment]
The new wireframes didn't have bread crumbs. Wondering what our thoughts are on that. We'd have to know the previous route(s) the user was on.

**Comment by swcurran** [comment]
I think we icebox this one for now.  Seems like a bigger one than needed.

FYI -- @DJ-Gordon
