### ISSUE TITLE
Recommendation for ordering of filter options on search screen

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/orgbook-bc-client#98]
The current order is Organization Type, Organization Status, Credential.
![image](https://user-images.githubusercontent.com/10504350/146931081-0145fb15-bba1-4936-bd20-7d22bb6c2182.png)

I'd recommend putting Organization Status at the top of the list.  The first thing I find myself doing all the time is filtering by Active status to remove all of the noise of the Historical companies.

Or perhaps put the Organization Status options at the top of the list and enable the Active option by default.  Unlike the previous UI this one lists the filter options at the top of the results, making it more obvious which filter options are being used.

**Comment by swcurran** [comment]
I think a lot of thought is needed for this. I had put in a few ideas I have on the same topic in #37, but I'm not convinced those are right either :-).  We'll have to discuss this one a bit to see both what's best and possible.

**Comment by swcurran** [comment]
Agree on this one change -- moving Org Status to the top of the list.  Priority for cleanup.
