### ISSUE TITLE
Credential verified link is incorrect for relationships / Related organizations linking to the wrong (expired) parent record.

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/orgbook-bc-client#99]
Example record: https://orgbook.gov.bc.ca/entity/BC0928747

Steps to reproduce:
- Navigate to the example record, or any other record with relationships.
- Click on any of the relationships to view the related organization's details.
- Scroll to the relationships section of the screen.
- Open the Credential status for a related organization.
- Hover over the Credential verified link.

Observed behavior:
- The link is `https://orgbook.gov.bc.ca/`
![image](https://user-images.githubusercontent.com/10504350/146933317-39bf1a56-c77a-4eb4-80ac-f56b03188103.png)

Expected behavior:
- The link to be the url of the organization's credential details page.  https://orgbook.gov.bc.ca/entity/BC0928747/credential/1485679 in the case of this example.

**Comment by WadeBarnes** [comment]
Further investigation indicates this is an issue with the related organization records themselves.  The issue occurs regardless of how you get to the related records in this example.  They are linking to the expired record of their parent organization rather than the active one.  This can be seen in the screen shot above **Effective: Dec 31, 1987** for https://orgbook.gov.bc.ca/entity/FM0414526.

In this example the active record for the parent organization is linking to the active DBA records, but all of the active DBA records are linking back to the expired record of the parent organization.

If you navigate from the parent organization to a related organization and then click on the relationship link to the parent organization this becomes more clear.

You see this:
![image](https://user-images.githubusercontent.com/10504350/146935581-8e413c3c-f0ef-49b3-a423-e54f297d2d0e.png)

Rather than returning to the record you started from:
![image](https://user-images.githubusercontent.com/10504350/146935702-998bccfe-941b-4ed6-806d-e3035154b579.png)

**Comment by WadeBarnes** [comment]
This is not an issue with the previous UI as is displays both parent relationships, the active one and the expired (archived) one.  This can currently be seen here; https://frontend-prod.apps.silver.devops.gov.bc.ca/en/organization/registration.registries.ca/FM0414526

**Comment by swcurran** [comment]
I see the expired issue and agree that it needs to be addressed.  Not sure I get the initial sequence as being wrong -- it's going to where I expect (except for landing on the expired record).

**Comment by WadeBarnes** [comment]
The initial sequence is talking about the incorrect link for Credential verified.  You go to the correct organization record, however that record's Credential verified is wrong, it will take you to the main search page, rather than the credential details for the organization you are viewing.

**Comment by swcurran** [comment]
Priority for cleanup

**Comment by wadeking98** [comment]
I think we should split this into two issues. The issue with the relationship linking back to an expired credential seems to be a data issue, whereas the "credential verified" link can be solved on the frontend.
